/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/objects/Ender5Pro.glb --types --keepnames --output src/components/scene/PrintingLevel/Ender5Pro.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['control-panel-stock_stock']: THREE.Mesh
    ['corner-bracket']: THREE.Mesh
    ['corner-bracket002']: THREE.Mesh
    ['corner-bracket003']: THREE.Mesh
    ['corner-bracket004']: THREE.Mesh
    ['corner-bracket005']: THREE.Mesh
    ['corner-bracket006']: THREE.Mesh
    ['drive-shaft-8mm']: THREE.Mesh
    ['drive-shaft-8mm002']: THREE.Mesh
    endcap: THREE.Mesh
    endcap002: THREE.Mesh
    endcap003: THREE.Mesh
    ['extruder-feed-arm']: THREE.Mesh
    ['extruder-feed-bracket']: THREE.Mesh
    ['extruder-mount-plate']: THREE.Mesh
    ['extruder-pivot-bushing']: THREE.Mesh
    ['extruder-spring-bushing']: THREE.Mesh
    ['filament-spool']: THREE.Mesh
    ['flanged-bearing-10mm']: THREE.Mesh
    ['flanged-bearing-10mm002']: THREE.Mesh
    frame: THREE.Mesh
    ['front-pulley-bracket-ndr']: THREE.Mesh
    ['front-pulley-bracket-ndr_MirrorDefault']: THREE.Mesh
    ['guide-rod']: THREE.Mesh
    ['guide-rod-bracket']: THREE.Mesh
    ['guide-rod-bracket002']: THREE.Mesh
    ['guide-rod-bracket003']: THREE.Mesh
    ['guide-rod-bracket004']: THREE.Mesh
    ['guide-rod002']: THREE.Mesh
    ['hose-fitting-4x6mm']: THREE.Mesh
    ['lead-screw']: THREE.Mesh
    ['limit-switch_large-plate']: THREE.Mesh
    ['limit-switch_small-plate']: THREE.Mesh
    ['limit-switch_small-plate002']: THREE.Mesh
    ['main-board']: THREE.Mesh
    ['pulley-half-ndr']: THREE.Mesh
    ['pulley-half-ndr002']: THREE.Mesh
    ['pulley-half-ndr_MirrorDefault']: THREE.Mesh
    ['pulley-half-ndr_MirrorDefault002']: THREE.Mesh
    ['rear-pulley-bracket']: THREE.Mesh
    ['rear-pulley-bracket_MirrorDefault']: THREE.Mesh
    ['rubber-foot']: THREE.Mesh
    ['rubber-foot002']: THREE.Mesh
    ['rubber-foot003']: THREE.Mesh
    ['rubber-foot004']: THREE.Mesh
    ['shaft-coupling']: THREE.Mesh
    ['shaft-coupling002']: THREE.Mesh
    ['shaft-coupling003']: THREE.Mesh
    ['spool-bracket']: THREE.Mesh
    ['spool-spindle']: THREE.Mesh
    ['spool-spindle-ring']: THREE.Mesh
    ['stepper-motor_large']: THREE.Mesh
    ['stepper-motor_large-double-shaft']: THREE.Mesh
    ['stepper-motor_small']: THREE.Mesh
    ['stepper-motor_small002']: THREE.Mesh
    ['toothed-pulley_8mm-shaft']: THREE.Mesh
    ['toothed-pulley_8mm-shaft002']: THREE.Mesh
    wheel: THREE.Mesh
    wheel002: THREE.Mesh
    wheel003: THREE.Mesh
    wheel004: THREE.Mesh
    wheel005: THREE.Mesh
    wheel006: THREE.Mesh
    wheel007: THREE.Mesh
    wheel008: THREE.Mesh
    wheel009: THREE.Mesh
    wheel010: THREE.Mesh
    wheel011: THREE.Mesh
    ['y-axis-belt']: THREE.Mesh
    ['y-axis-belt_MirrorDefault']: THREE.Mesh
    ['y-axis-stepper-bracket']: THREE.Mesh
    ['z-axis-stepper-bracket']: THREE.Mesh
    ['z-axis-strut-20x20_bottom']: THREE.Mesh
    ['z-axis-strut-20x20_top']: THREE.Mesh
    ['heater-plate']: THREE.Mesh
    ['lead-screw-nut']: THREE.Mesh
    ['leveling-wheel']: THREE.Mesh
    ['leveling-wheel002']: THREE.Mesh
    ['leveling-wheel003']: THREE.Mesh
    ['leveling-wheel004']: THREE.Mesh
    ['magnetic-plate']: THREE.Mesh
    ['sub-plate']: THREE.Mesh
    ['z-axis-bearing-plate']: THREE.Mesh
    ['fan-shroud']: THREE.Mesh
    ['heat-break']: THREE.Mesh
    ['heat-sink']: THREE.Mesh
    ['hose-fitting-4x10mm']: THREE.Mesh
    ['hot-end-boot']: THREE.Mesh
    ['hot-end-carriage-plate']: THREE.Mesh
    ['hot-end-fan']: THREE.Mesh
    ['hot-end-heater-block']: THREE.Mesh
    ['nozzle-04']: THREE.Mesh
    ['part-cooling-fan']: THREE.Mesh
    ['part-fan-duct']: THREE.Mesh
    ['x-axis-belt']: THREE.Mesh
    ['pulley-half']: THREE.Mesh
    ['pulley-half002']: THREE.Mesh
    ['toothed-pulley']: THREE.Mesh
    ['x-axis-pulley-mount']: THREE.Mesh
    ['x-axis-stepper-cover']: THREE.Mesh
    ['x-axis-stepper-mount_pulley-side']: THREE.Mesh
    ['x-axis-stepper-mount_stepper-side']: THREE.Mesh
    ['x-axis-strut']: THREE.Mesh
    ['extruder-gear']: THREE.Mesh
    ['extruder-pulley']: THREE.Mesh
  }
  materials: {
    plas: THREE.MeshStandardMaterial
    alu: THREE.MeshStandardMaterial
    accent: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  // Pure geometry: the GLB's named rig hierarchy (Bed_Z / GantryY / CarriageX)
  // is rendered here; PrintingLevel owns the single AnimationMixer that scrubs
  // the clips, so this component deliberately does NOT bind useAnimations.
  const { nodes, materials } = useGLTF('/assets/objects/Ender5Pro.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Print">
        <group name="Frame_Static" position={[-0.05, 0.311, -0.063]}>
          <mesh name="control-panel-stock_stock" geometry={nodes['control-panel-stock_stock'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="corner-bracket" geometry={nodes['corner-bracket'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="corner-bracket002" geometry={nodes['corner-bracket002'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="corner-bracket003" geometry={nodes['corner-bracket003'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="corner-bracket004" geometry={nodes['corner-bracket004'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="corner-bracket005" geometry={nodes['corner-bracket005'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="corner-bracket006" geometry={nodes['corner-bracket006'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="drive-shaft-8mm" geometry={nodes['drive-shaft-8mm'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="drive-shaft-8mm002" geometry={nodes['drive-shaft-8mm002'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="endcap" geometry={nodes.endcap.geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="endcap002" geometry={nodes.endcap002.geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="endcap003" geometry={nodes.endcap003.geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="extruder-feed-arm" geometry={nodes['extruder-feed-arm'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="extruder-feed-bracket" geometry={nodes['extruder-feed-bracket'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="extruder-mount-plate" geometry={nodes['extruder-mount-plate'].geometry} material={materials.glass} position={[0.05, -0.311, 0.063]} />
          <mesh name="extruder-pivot-bushing" geometry={nodes['extruder-pivot-bushing'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="extruder-spring-bushing" geometry={nodes['extruder-spring-bushing'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="filament-spool" geometry={nodes['filament-spool'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="flanged-bearing-10mm" geometry={nodes['flanged-bearing-10mm'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="flanged-bearing-10mm002" geometry={nodes['flanged-bearing-10mm002'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="frame" geometry={nodes.frame.geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="front-pulley-bracket-ndr" geometry={nodes['front-pulley-bracket-ndr'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="front-pulley-bracket-ndr_MirrorDefault" geometry={nodes['front-pulley-bracket-ndr_MirrorDefault'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="guide-rod" geometry={nodes['guide-rod'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="guide-rod-bracket" geometry={nodes['guide-rod-bracket'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="guide-rod-bracket002" geometry={nodes['guide-rod-bracket002'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="guide-rod-bracket003" geometry={nodes['guide-rod-bracket003'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="guide-rod-bracket004" geometry={nodes['guide-rod-bracket004'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="guide-rod002" geometry={nodes['guide-rod002'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="hose-fitting-4x6mm" geometry={nodes['hose-fitting-4x6mm'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="lead-screw" geometry={nodes['lead-screw'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="limit-switch_large-plate" geometry={nodes['limit-switch_large-plate'].geometry} material={materials.glass} position={[0.05, -0.311, 0.063]} />
          <mesh name="limit-switch_small-plate" geometry={nodes['limit-switch_small-plate'].geometry} material={materials.glass} position={[0.05, -0.311, 0.063]} />
          <mesh name="limit-switch_small-plate002" geometry={nodes['limit-switch_small-plate002'].geometry} material={materials.glass} position={[0.05, -0.311, 0.063]} />
          <mesh name="main-board" geometry={nodes['main-board'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="pulley-half-ndr" geometry={nodes['pulley-half-ndr'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="pulley-half-ndr002" geometry={nodes['pulley-half-ndr002'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="pulley-half-ndr_MirrorDefault" geometry={nodes['pulley-half-ndr_MirrorDefault'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="pulley-half-ndr_MirrorDefault002" geometry={nodes['pulley-half-ndr_MirrorDefault002'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="rear-pulley-bracket" geometry={nodes['rear-pulley-bracket'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="rear-pulley-bracket_MirrorDefault" geometry={nodes['rear-pulley-bracket_MirrorDefault'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="rubber-foot" geometry={nodes['rubber-foot'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="rubber-foot002" geometry={nodes['rubber-foot002'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="rubber-foot003" geometry={nodes['rubber-foot003'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="rubber-foot004" geometry={nodes['rubber-foot004'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="shaft-coupling" geometry={nodes['shaft-coupling'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="shaft-coupling002" geometry={nodes['shaft-coupling002'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="shaft-coupling003" geometry={nodes['shaft-coupling003'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="spool-bracket" geometry={nodes['spool-bracket'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="spool-spindle" geometry={nodes['spool-spindle'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="spool-spindle-ring" geometry={nodes['spool-spindle-ring'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="stepper-motor_large" geometry={nodes['stepper-motor_large'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="stepper-motor_large-double-shaft" geometry={nodes['stepper-motor_large-double-shaft'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="stepper-motor_small" geometry={nodes['stepper-motor_small'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="stepper-motor_small002" geometry={nodes['stepper-motor_small002'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="toothed-pulley_8mm-shaft" geometry={nodes['toothed-pulley_8mm-shaft'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="toothed-pulley_8mm-shaft002" geometry={nodes['toothed-pulley_8mm-shaft002'].geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="wheel" geometry={nodes.wheel.geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="wheel002" geometry={nodes.wheel002.geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="wheel003" geometry={nodes.wheel003.geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="wheel004" geometry={nodes.wheel004.geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="wheel005" geometry={nodes.wheel005.geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="wheel006" geometry={nodes.wheel006.geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="wheel007" geometry={nodes.wheel007.geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="wheel008" geometry={nodes.wheel008.geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="wheel009" geometry={nodes.wheel009.geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="wheel010" geometry={nodes.wheel010.geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="wheel011" geometry={nodes.wheel011.geometry} material={materials.accent} position={[0.05, -0.311, 0.063]} />
          <mesh name="y-axis-belt" geometry={nodes['y-axis-belt'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="y-axis-belt_MirrorDefault" geometry={nodes['y-axis-belt_MirrorDefault'].geometry} material={materials.plas} position={[0.05, -0.311, 0.063]} />
          <mesh name="y-axis-stepper-bracket" geometry={nodes['y-axis-stepper-bracket'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="z-axis-stepper-bracket" geometry={nodes['z-axis-stepper-bracket'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="z-axis-strut-20x20_bottom" geometry={nodes['z-axis-strut-20x20_bottom'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
          <mesh name="z-axis-strut-20x20_top" geometry={nodes['z-axis-strut-20x20_top'].geometry} material={materials.alu} position={[0.05, -0.311, 0.063]} />
        </group>
        <group name="Bed_Z" position={[-0.096, 0.257, -0.001]}>
          <mesh name="heater-plate" geometry={nodes['heater-plate'].geometry} material={materials.glass} position={[0.096, -0.257, 0.001]} />
          <mesh name="lead-screw-nut" geometry={nodes['lead-screw-nut'].geometry} material={materials.accent} position={[0.096, -0.257, 0.001]} />
          <mesh name="leveling-wheel" geometry={nodes['leveling-wheel'].geometry} material={materials.accent} position={[0.096, -0.257, 0.001]} />
          <mesh name="leveling-wheel002" geometry={nodes['leveling-wheel002'].geometry} material={materials.accent} position={[0.096, -0.257, 0.001]} />
          <mesh name="leveling-wheel003" geometry={nodes['leveling-wheel003'].geometry} material={materials.accent} position={[0.096, -0.257, 0.001]} />
          <mesh name="leveling-wheel004" geometry={nodes['leveling-wheel004'].geometry} material={materials.accent} position={[0.096, -0.257, 0.001]} />
          <mesh name="magnetic-plate" geometry={nodes['magnetic-plate'].geometry} material={materials.glass} position={[0.096, -0.257, 0.001]} />
          <mesh name="sub-plate" geometry={nodes['sub-plate'].geometry} material={materials.glass} position={[0.096, -0.257, 0.001]} />
          <mesh name="z-axis-bearing-plate" geometry={nodes['z-axis-bearing-plate'].geometry} material={materials.glass} position={[0.096, -0.257, 0.001]} />
        </group>
        <group name="GantryY" position={[-0.116, 0.472, 0.067]}>
          <group name="CarriageX" position={[0.026, -0.011, 0.03]}>
            <mesh name="fan-shroud" geometry={nodes['fan-shroud'].geometry} material={materials.plas} position={[0.09, -0.462, -0.042]} />
            <mesh name="heat-break" geometry={nodes['heat-break'].geometry} material={materials.accent} position={[0.09, -0.462, -0.042]} />
            <mesh name="heat-sink" geometry={nodes['heat-sink'].geometry} material={materials.accent} position={[0.09, -0.462, -0.042]} />
            <mesh name="hose-fitting-4x10mm" geometry={nodes['hose-fitting-4x10mm'].geometry} material={materials.plas} position={[0.09, -0.462, -0.042]} />
            <mesh name="hot-end-boot" geometry={nodes['hot-end-boot'].geometry} material={materials.accent} position={[0.09, -0.462, -0.042]} />
            <mesh name="hot-end-carriage-plate" geometry={nodes['hot-end-carriage-plate'].geometry} material={materials.glass} position={[0.09, -0.462, -0.042]} />
            <mesh name="hot-end-fan" geometry={nodes['hot-end-fan'].geometry} material={materials.accent} position={[0.09, -0.462, -0.042]} />
            <mesh name="hot-end-heater-block" geometry={nodes['hot-end-heater-block'].geometry} material={materials.accent} position={[0.09, -0.462, -0.042]} />
            <mesh name="nozzle-04" geometry={nodes['nozzle-04'].geometry} material={materials.accent} position={[0.09, -0.462, -0.042]} />
            <mesh name="part-cooling-fan" geometry={nodes['part-cooling-fan'].geometry} material={materials.plas} position={[0.09, -0.462, -0.042]} />
            <mesh name="part-fan-duct" geometry={nodes['part-fan-duct'].geometry} material={materials.plas} position={[0.09, -0.462, -0.042]} />
            <mesh name="x-axis-belt" geometry={nodes['x-axis-belt'].geometry} material={materials.plas} position={[0.09, -0.462, -0.042]} />
          </group>
          <mesh name="pulley-half" geometry={nodes['pulley-half'].geometry} material={materials.accent} position={[0.116, -0.472, -0.012]} />
          <mesh name="pulley-half002" geometry={nodes['pulley-half002'].geometry} material={materials.accent} position={[0.116, -0.472, -0.012]} />
          <mesh name="toothed-pulley" geometry={nodes['toothed-pulley'].geometry} material={materials.accent} position={[0.116, -0.472, -0.012]} />
          <mesh name="x-axis-pulley-mount" geometry={nodes['x-axis-pulley-mount'].geometry} material={materials.accent} position={[0.116, -0.472, -0.012]} />
          <mesh name="x-axis-stepper-cover" geometry={nodes['x-axis-stepper-cover'].geometry} material={materials.plas} position={[0.116, -0.472, -0.012]} />
          <mesh name="x-axis-stepper-mount_pulley-side" geometry={nodes['x-axis-stepper-mount_pulley-side'].geometry} material={materials.accent} position={[0.116, -0.472, -0.012]} />
          <mesh name="x-axis-stepper-mount_stepper-side" geometry={nodes['x-axis-stepper-mount_stepper-side'].geometry} material={materials.plas} position={[0.116, -0.472, -0.012]} />
          <mesh name="x-axis-strut" geometry={nodes['x-axis-strut'].geometry} material={materials.alu} position={[0.116, -0.472, -0.012]} />
        </group>
        <group name="Extruder_Spin" position={[0.122, 0.363, -0.157]}>
          <mesh name="extruder-gear" geometry={nodes['extruder-gear'].geometry} material={materials.accent} position={[-0.122, -0.363, 0.157]} />
          <mesh name="extruder-pulley" geometry={nodes['extruder-pulley'].geometry} material={materials.accent} position={[-0.122, -0.363, 0.157]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/objects/Ender5Pro.glb')
