/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 blender/assets/Ender5Pro.raw.glb -T -S --ratio 0.4 --error 0.001 -t -k -o apps/client/src/components/scene/PrintingLevel/Ender5Pro.tsx 
Files: blender/assets/Ender5Pro.raw.glb [45.65MB] > /Users/ryanoboyle/LayerDynamics/apps/client/src/components/scene/PrintingLevel/Ender5Pro.raw-transformed.glb [2.1MB] (95%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['heater-plate']: THREE.Mesh
    ['lead-screw-nut']: THREE.Mesh
    ['fan-shroud']: THREE.Mesh
    ['heat-break']: THREE.Mesh
    ['hot-end-carriage-plate']: THREE.Mesh
    ['pulley-half']: THREE.Mesh
    ['x-axis-stepper-cover']: THREE.Mesh
    ['x-axis-strut']: THREE.Mesh
    ['control-panel-stock_stock']: THREE.Mesh
    ['corner-bracket']: THREE.Mesh
    ['drive-shaft-8mm']: THREE.Mesh
    ['extruder-mount-plate']: THREE.Mesh
  }
  materials: {
    glass: THREE.MeshStandardMaterial
    accent: THREE.MeshStandardMaterial
    plas: THREE.MeshStandardMaterial
    alu: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  // Pure geometry from the gltfjsx -T (joined + meshopt-simplified + Draco) GLB.
  // PrintingLevel owns the single AnimationMixer that scrubs the Bed_Z / GantryY /
  // CarriageX clips, so this component deliberately does NOT bind useAnimations.
  const { nodes, materials } = useGLTF('/assets/objects/Ender5Pro.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Print">
        <group name="Bed_Z" position={[-0.096, 0.257, -0.001]}>
          <mesh name="heater-plate" geometry={nodes['heater-plate'].geometry} material={materials.glass} position={[0.096, -0.257, 0.001]} />
          <mesh name="lead-screw-nut" geometry={nodes['lead-screw-nut'].geometry} material={materials.accent} position={[0.096, -0.257, 0.001]} />
        </group>
        <group name="GantryY" position={[-0.116, 0.472, 0.067]}>
          <group name="CarriageX" position={[0.026, -0.011, 0.03]}>
            <mesh name="fan-shroud" geometry={nodes['fan-shroud'].geometry} material={materials.plas} position={[0.09, -0.462, -0.042]} />
            <mesh name="heat-break" geometry={nodes['heat-break'].geometry} material={materials.accent} position={[0.09, -0.462, -0.042]} />
            <mesh name="hot-end-carriage-plate" geometry={nodes['hot-end-carriage-plate'].geometry} material={materials.glass} position={[0.09, -0.462, -0.042]} />
          </group>
          <mesh name="pulley-half" geometry={nodes['pulley-half'].geometry} material={materials.accent} position={[0.116, -0.472, -0.012]} />
          <mesh name="x-axis-stepper-cover" geometry={nodes['x-axis-stepper-cover'].geometry} material={materials.plas} position={[0.116, -0.472, -0.012]} />
          <mesh name="x-axis-strut" geometry={nodes['x-axis-strut'].geometry} material={materials.alu} position={[0.116, -0.472, -0.012]} />
        </group>
        <mesh name="control-panel-stock_stock" geometry={nodes['control-panel-stock_stock'].geometry} material={materials.plas} />
        <mesh name="corner-bracket" geometry={nodes['corner-bracket'].geometry} material={materials.alu} />
        <mesh name="drive-shaft-8mm" geometry={nodes['drive-shaft-8mm'].geometry} material={materials.accent} />
        <mesh name="extruder-mount-plate" geometry={nodes['extruder-mount-plate'].geometry} material={materials.glass} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/objects/Ender5Pro.glb')
